# Generated by Django 5.2.8 on 2025-12-05 05:03

from django.db import migrations


def cleanup_duplicate_pending_offers(apps, schema_editor):
    """
    Remove duplicate pending offers for the same content/buyer combination.
    Keep the most recent one, mark older ones as rejected.
    """
    Offer = apps.get_model('offers', 'Offer')
    from django.db.models import Count

    # Find content/buyer combinations with multiple pending offers
    duplicates = (
        Offer.objects.filter(status='pending')
        .values('content_id', 'buyer_id')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )

    for dup in duplicates:
        # Get all pending offers for this content/buyer combination
        offers = Offer.objects.filter(
            content_id=dup['content_id'],
            buyer_id=dup['buyer_id'],
            status='pending'
        ).order_by('-created_at')  # Most recent first

        # Keep the first (most recent), reject the rest
        offers_to_reject = list(offers[1:])
        for offer in offers_to_reject:
            offer.status = 'rejected'
            offer.producer_response = 'Automatically rejected due to newer offer from same buyer'
            offer.save(update_fields=['status', 'producer_response', 'updated_at'])


def reverse_cleanup(apps, schema_editor):
    """
    Reverse is not possible - we can't restore the rejected offers
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_remove_offer_unique_pending_offer_per_content_buyer'),
    ]

    operations = [
        migrations.RunPython(cleanup_duplicate_pending_offers, reverse_cleanup),
    ]
