# Generated by Django 5.2.8 on 2025-12-05 05:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_cleanup_duplicate_pending_offers'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('content', 'buyer'), name='unique_pending_offer_per_content_buyer'),
        ),
    ]
