# Generated by Django 5.2.8 on 2025-12-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_country_user_genre_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='booth_slug',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Booth slug'),
        ),
    ]
