# Generated by Django 5.2.8 on 2025-12-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_booth_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('creator', 'Producer'), ('buyer', 'Buyer'), ('admin', 'Admin')], default='creator', max_length=20, verbose_name='Role'),
        ),
    ]
