# Generated by Django 5.2.8 on 2025-12-01 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Booth slug')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View count')),
                ('is_boosted', models.BooleanField(default=False, verbose_name='Is boosted')),
                ('boost_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Boost expires at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('producer', models.OneToOneField(limit_choices_to={'role': 'creator'}, on_delete=django.db.models.deletion.CASCADE, related_name='booth', to=settings.AUTH_USER_MODEL, verbose_name='Producer')),
            ],
            options={
                'verbose_name': 'Booth',
                'verbose_name_plural': 'Booths',
                'ordering': ['-created_at'],
            },
        ),
    ]
