# Generated by Django 5.2.8 on 2025-12-01 02:00

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Thumbnail')),
                ('genre_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), help_text='1-3 genre tags', size=3, verbose_name='Genre tags')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('KRW', 'Korean Won'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen')], default='USD', max_length=3, verbose_name='Currency')),
                ('duration_seconds', models.PositiveIntegerField(help_text='Video duration in seconds', verbose_name='Duration (seconds)')),
                ('video_url', models.URLField(blank=True, help_text='URL to video preview or full video', max_length=500, verbose_name='Video URL')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('public', 'Public'), ('deleted', 'Deleted')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View count')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('producer', models.ForeignKey(limit_choices_to={'role': 'creator'}, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL, verbose_name='Producer')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='contents_co_status_b12b6b_idx'), models.Index(fields=['producer', 'status'], name='contents_co_produce_8f856f_idx')],
            },
        ),
    ]
