# Generated by Django 5.2.8 on 2025-12-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_remove_content_thumbnail_content_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='teaser_video',
            field=models.FileField(blank=True, help_text='Short teaser/trailer video file', null=True, upload_to='teasers/', verbose_name='Teaser video'),
        ),
    ]
