# Generated by Django 5.2.8 on 2025-12-01 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Document number')),
                ('content_title', models.CharField(max_length=200, verbose_name='Content title')),
                ('content_description', models.TextField(verbose_name='Content description')),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Agreed price')),
                ('currency', models.CharField(max_length=3, verbose_name='Currency')),
                ('buyer_company', models.CharField(max_length=200, verbose_name='Buyer company')),
                ('buyer_country', models.CharField(max_length=100, verbose_name='Buyer country')),
                ('producer_company', models.CharField(max_length=200, verbose_name='Producer company')),
                ('producer_country', models.CharField(max_length=100, verbose_name='Producer country')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='loi_pdfs/', verbose_name='PDF file')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='PDF generated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_lois', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loi', to='offers.offer', verbose_name='Offer')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_lois', to=settings.AUTH_USER_MODEL, verbose_name='Producer')),
            ],
            options={
                'verbose_name': 'LOI',
                'verbose_name_plural': 'LOIs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['buyer', '-created_at'], name='loi_loi_buyer_i_25b042_idx'), models.Index(fields=['producer', '-created_at'], name='loi_loi_produce_a8887d_idx')],
            },
        ),
    ]
